name: 期刊订阅自动同步

on:
  schedule:
    # 每周一北京时间上午9点 (UTC+8 = UTC+0 - 8小时 = 01:00 UTC)
    - cron: '0 1 * * 1'
  
  # 允许手动触发
  workflow_dispatch:

jobs:
  sync-journals:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      
      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: 运行期刊同步
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          NOTION_DB_SUBSCRIPTIONS: ${{ secrets.NOTION_DB_SUBSCRIPTIONS }}
          NOTION_DB_ARTICLES: ${{ secrets.NOTION_DB_ARTICLES }}
          NOTION_DB_SUMMARIES: ${{ secrets.NOTION_DB_SUMMARIES }}
        run: python journal_subscription_v2.py
      
      - name: 上传运行日志
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sync-logs-${{ github.run_number }}
          path: |
            *.log
          retention-days: 30
